#Default values for deep-challenge-api

nameOverride: deel-api
replicaCount: 1
baseDomain: deel.local

aws:
  region: us-east-1

image:
  # repository: lakeside763/deel
  repository: 544025436226.dkr.ecr.us-east-1.amazonaws.com/deel
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  name: deel-api-depl

service:
  name: deel-api-svc
  http: 
    type: NodePort
    containerPort: 4500
    name: deel-api-svc
    scheme: internet-facing
    servicePort: 80
  https: 
    type: NodePort
    containerPort: 4500
    name: deel-api-svc
    scheme: internet-facing
    servicePort: 433
  type: NodePort

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 100Mi
  # limits:
  #   cpu: 200m
  #   memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}